/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.List;
import model.Word;

/**
 *
 * @author vinicius
 */
public class NewSintagmaFrame extends javax.swing.JFrame 
{
    private List<Word> words;
    private Word selected;
    
    /**
     * Creates new form NewSSintagmaFrame
     * @param words Array de words a ser copiado
     */
    public NewSintagmaFrame(List<Word> words) 
    {
        initComponents();
        this.words = new ArrayList<>(words);
        selected = null;
        buttonSplitPane.setDividerLocation(0.5);
        for(int i=0;i<words.size();i++)
            selectNucleo.addItem(words.get(i));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButton1 = new javax.swing.JButton();
        frameInfo = new javax.swing.JLabel();
        selectNucleo = new javax.swing.JComboBox<>();
        buttonSplitPane = new javax.swing.JSplitPane();
        cancelSelection = new javax.swing.JButton();
        confirmSelection = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFont(new java.awt.Font("Abyssinica SIL", 1, 10)); // NOI18N
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0};
        layout.rowHeights = new int[] {0, 5, 0, 5, 0};
        getContentPane().setLayout(layout);

        frameInfo.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        frameInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        frameInfo.setText("Selecione o núcleo do sintagma");
        frameInfo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(frameInfo, gridBagConstraints);

        selectNucleo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectNucleoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(selectNucleo, gridBagConstraints);

        buttonSplitPane.setDividerLocation(100);
        buttonSplitPane.setResizeWeight(0.5);

        cancelSelection.setText("Cancelar");
        cancelSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelSelectionActionPerformed(evt);
            }
        });
        buttonSplitPane.setLeftComponent(cancelSelection);

        confirmSelection.setText("Confirmar núcleo");
        confirmSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmSelectionActionPerformed(evt);
            }
        });
        buttonSplitPane.setRightComponent(confirmSelection);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(buttonSplitPane, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectNucleoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectNucleoActionPerformed
        selected = (Word) selectNucleo.getSelectedItem();
    }//GEN-LAST:event_selectNucleoActionPerformed

    private void confirmSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmSelectionActionPerformed
        if(selected != null) 
        {
            dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));            
        }
    }//GEN-LAST:event_confirmSelectionActionPerformed

    private void cancelSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelSelectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelSelectionActionPerformed
    
    public void setWords(List<Word> words)
    {
        this.words = words;
        selectNucleo.removeAllItems();
        for(int i=0;i<words.size();i++)
            selectNucleo.addItem(words.get(i));
    }
    
    public Word getSelection()
    {
        return selected;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane buttonSplitPane;
    private javax.swing.JButton cancelSelection;
    private javax.swing.JButton confirmSelection;
    private javax.swing.JLabel frameInfo;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<Word> selectNucleo;
    // End of variables declaration//GEN-END:variables
}
